<%@ Page Language="C#" MasterPageFile="~/MasterPageadmin.master" AutoEventWireup="true" CodeFile="sf1.aspx.cs" Inherits="sf1" Title="Untitled Page" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" Runat="Server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" Runat="Server">

<asp:GridView ID="GridView1" runat="server" AutoGenerateColumns="False" 
            BackColor="White" BorderColor="#3366CC" BorderStyle="None" BorderWidth="1px" 
            CellPadding="4" onselectedindexchanged="GridView1_SelectedIndexChanged" 
            AutoGenerateDeleteButton="True" onrowdeleting="GridView1_RowDeleting">
            <RowStyle BackColor="White" ForeColor="#003399" />
            <FooterStyle BackColor="#99CCCC" ForeColor="#003399" />
            <PagerStyle BackColor="#99CCCC" ForeColor="#003399" HorizontalAlign="Left" />
            <SelectedRowStyle BackColor="#009999" Font-Bold="True" ForeColor="#CCFF99" />
            <HeaderStyle BackColor="#003399" Font-Bold="True" ForeColor="#CCCCFF" />
            <Columns>
       
           
            <asp:TemplateField HeaderText="name">
            <ItemTemplate>
                <asp:HiddenField ID="hf" runat="server" value='<%# Eval("id") %>' />
             <asp:Label ID="Lblname" runat="server" Text='<%# Eval("name") %>'></asp:Label>
            </ItemTemplate>
            </asp:TemplateField>
           
            <asp:TemplateField HeaderText="password">
            <ItemTemplate>
                <asp:Label ID="Lblpass" runat="server" Text='<%# Eval("password") %>'></asp:Label>
            </ItemTemplate>
            </asp:TemplateField>
            
           
            
            <asp:TemplateField HeaderText="email id">
            <ItemTemplate>
                <asp:Label ID="Lblemail" runat="server" Text='<%# Eval("email") %>'></asp:Label>
            </ItemTemplate>
            </asp:TemplateField>
            
            <asp:TemplateField HeaderText="question">
            <ItemTemplate>
                <asp:Label ID="Lblques" runat="server" Text='<%# Eval("question") %>'></asp:Label>
            </ItemTemplate>
            </asp:TemplateField>
            
            <asp:TemplateField HeaderText="answer">
            <ItemTemplate>
                <asp:Label ID="Lblans" runat="server" Text='<%# Eval("answer") %>'></asp:Label>
            </ItemTemplate>
            </asp:TemplateField>
            
          
           
            </Columns>
        </asp:GridView>

</asp:Content>

