<%@ Page Language="C#" MasterPageFile="~/MasterPageadmin.master" AutoEventWireup="true" CodeFile="uf1.aspx.cs" Inherits="uf1" Title="Untitled Page" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" Runat="Server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" Runat="Server">
<asp:GridView ID="GridView1" runat="server" AutoGenerateColumns="False" 
            BackColor="White" BorderColor="#3366CC" BorderStyle="None" BorderWidth="1px" 
            CellPadding="4" onselectedindexchanged="GridView1_SelectedIndexChanged" 
            AutoGenerateDeleteButton="True" onrowdeleting="GridView1_RowDeleting" onrowcancelingedit="GridView1_RowCancelingEdit" 
        onrowediting="GridView1_RowEditing" onrowupdating="GridView1_RowUpdating">
            <RowStyle BackColor="White" ForeColor="#003399" />
            <FooterStyle BackColor="#99CCCC" ForeColor="#003399" />
            <PagerStyle BackColor="#99CCCC" ForeColor="#003399" HorizontalAlign="Left" />
            <SelectedRowStyle BackColor="#009999" Font-Bold="True" ForeColor="#CCFF99" />
            <HeaderStyle BackColor="#003399" Font-Bold="True" ForeColor="#CCCCFF" />
            <Columns>
       
           
            <asp:TemplateField HeaderText="name">
            <ItemTemplate>
                <asp:HiddenField ID="hf" runat="server" value='<%# Eval("id") %>' />
             <asp:Label ID="Lblname" runat="server" Text='<%# Eval("name") %>'></asp:Label>
            
            </ItemTemplate>
            <EditItemTemplate>
            <asp:HiddenField ID="hf1" runat="server" value='<%# Eval("id") %>' />
                <asp:TextBox ID="Txtname" runat="server" Text='<%# Eval("name") %>'></asp:TextBox>
            </EditItemTemplate>
            </asp:TemplateField>
           
            <asp:TemplateField HeaderText="surname">
            <ItemTemplate>
                <asp:Label ID="Lblsur" runat="server" Text='<%# Eval("surname") %>'></asp:Label>
            </ItemTemplate>
            </asp:TemplateField>
            
            <asp:TemplateField HeaderText="telephone">
            <ItemTemplate>
                <asp:Label ID="Lbltel" runat="server" Text='<%# Eval("tel") %>'></asp:Label>
            </ItemTemplate>
            </asp:TemplateField>
            
            <asp:TemplateField HeaderText="email id">
            <ItemTemplate>
                <asp:Label ID="Lblemail" runat="server" Text='<%# Eval("emailid") %>'></asp:Label>
            </ItemTemplate>
            </asp:TemplateField>
            
            <asp:TemplateField HeaderText="about us">
            <ItemTemplate>
                <asp:Label ID="Lblabtus" runat="server" Text='<%# Eval("aboutus") %>'></asp:Label>
            </ItemTemplate>
            </asp:TemplateField>
            
            <asp:TemplateField HeaderText="data availability">
            <ItemTemplate>
                <asp:Label ID="Lblda" runat="server" Text='<%# Eval("dataAvailability") %>'></asp:Label>
            </ItemTemplate>
            </asp:TemplateField>
            
            <asp:TemplateField HeaderText="packages">
            <ItemTemplate>
                <asp:Label ID="Lblpa" runat="server" Text='<%# Eval("packages") %>'></asp:Label>
            </ItemTemplate>
            </asp:TemplateField>
            
            <asp:TemplateField HeaderText="appearance">
            <ItemTemplate>
                <asp:Label ID="Lblsurname" runat="server" Text='<%# Eval("appearance") %>'></asp:Label>
            </ItemTemplate>
            </asp:TemplateField>
            
            <asp:TemplateField HeaderText="services">
            <ItemTemplate>
                <asp:Label ID="Lblser" runat="server" Text='<%# Eval("services") %>'></asp:Label>
            </ItemTemplate>
            </asp:TemplateField>

           
            </Columns>
        </asp:GridView>

</asp:Content>

